### ISSUE TITLE
language wrapping issue

### ISSUE THREAD

**Issue by progman1** [srenevey/neuro#2]
I've been writing a wrapper for your library for the OCaml language and have encountered an issue.
so my problem, not yours! 
but perhaps you would give it some consideration...
in:
```
    pub fn new<L: 'static + Loss, O: 'static + Optimizer>(input_shape: Dim,
               loss_function: L,
               optimizer: O,
               regularizer: Option<Regularizer>
    ) -> Result<Network, Error> {

        Ok(Network {
            layers: Vec::new(),
            loss_function: Box::new(loss_function),
            optimizer: Box::new(optimizer),
...
```
the parameters loss_function/optimizer being defined the way they are means (I think) that the call is specialised at each call site. for me that means I cannot wrap with a function and pass those parameters through - there is no way to take in these values generically.
matters would be easy if the parameters were defined as dynamically sized:
```
               loss_function: Box<dyn Loss>,
               optimizer: Box<dyn Optimizer>, 
               ...
```
and the 'new' function does this boxing anyway internally.
is this a change you could consider?

**Comment by srenevey** [comment]
I need to thing about it. My concern is the runtime cost associated with dynamic binding but that should not be too bad.

**Comment by progman1** [comment]
I got concerned in turn!
to try to get around the interfacing problem I implemented a macro hack to replicate the nn.new call as many times as there were combinations of losses and optimizers - 5 x 4!   unfortunately that didn't work out because I couldn't get the macro call to nest (once for each argument to nn.new defined by a trait).
but then I found a crate for wrapping in a discriminated union (which the author benched to be an improvement of 10x over dynamic dispatch).
except I did this to the neuro source substituting types Optimizer, Losses, DataSet and Layer - all the dynamics,
and tested on cifar10. result: no difference!  if i knew the territory better I might have known that dynamic dispatch
would account for a very minor part of the computation pie without implementing this.  
but not a total waste of time as I got a little rustier in the process.

and I eventually looked at the nn.new function and saw that the loss/optimizer arguments are just passed through to
the struct - so dynamic dispatch was already there!
so in requesting a type signature change from traited arguments to Box<dyn ..> there is no performance loss involved
at all. It just makes the inferface cleaner (arguably!) and eliminates 5 x 4 identical calls on my side :)

**Comment by srenevey** [comment]
Ok thanks for the update. I've modified the method signature in 079a64050dabd21a83b15b077686f18d783039b9. Let me know if that solves the issue you were facing.

**Comment by progman1** [comment]
All good.
Could you consider same for DataSet too?

**Comment by srenevey** [comment]
The current implementation of DataSet is the most idiomatic. Wrapping everything in Boxes to manually allocate on the heap is not necessary.
