### ISSUE TITLE
Building gives HDF5-sys error

### ISSUE THREAD

**Issue by RajashekarY** [srenevey/neuro#6]
I have installed HDF5 and  ArrayFire but still I'm unable to build my project it is just MNIST example from your site
![Screenshot from 2020-07-22 21-54-58](https://user-images.githubusercontent.com/15843662/88202470-8d71d700-cc66-11ea-92dd-8cf23de3b863.png)

## My /opt Directory has both of the dependencies too
![Screenshot from 2020-07-22 21-59-35](https://user-images.githubusercontent.com/15843662/88202597-c01bcf80-cc66-11ea-896a-4d70410a426f.png)
 Can you Please let me know where I'm doing mistake?

**Comment by srenevey** [comment]
Please try to define the HDF5_DIR environment variable with your path (i.e. `export HDF5_DIR=/opt/HDF5-1.12.0-Linux`) and see if that helps.

**Comment by RajashekarY** [comment]
Hey Thanks for responding I have solved the issue there are multiple changes needed to do everything was due to HDF5 installation

1. I followed [this](http://depts.washington.edu/cssuwb/wiki/linux_hdf5_installation) for Installation 
2. after that added this line `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/hdf5/hdf5-1.8.21/lib/`  to` ~/bashrc` 
3. `sudo mkdir /usr/lib/x86_64-linux-gnu/hdf5/serial -p`
4. `sudo cp -r /opt/hdf5/hdf5-1.8.21/lib/* /usr/lib/x86_64-linux-gnu/hdf5/serial/`
and ran cargo clean and cargo run
